[package]
name = "ray_marcher"
version = "0.1.0"
authors = ["pearisgreen <gerrit.proessl@gmail.com>"]
edition = "2018"

[dependencies]

piston_window = "0.89.0"
image = "0.21.0"
piston2d-sprite = "0.50.0"
gfx = "0.17.1"
gfx_device_gl = "0.15.0"
